title: DJYX License System
description: Comprehensive open-source license system with two distinct licensing models
url: "https://binceenigne.github.io"
baseurl: "/DJYX-License"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files
exclude:
  - README.md
  - README.zh-CN.md
  - .gitignore

# Include files
include:
  - _pages

# Collections
collections:
  licenses:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
